name: rust checker

on: [push]

jobs: 
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install rust environment
        uses: dtolnay/rust-toolchain@stable
      - name: compile checker
        run: cargo check  
      - name: run test
        run: cargo test
